<?php

namespace Tests\Feature;

use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;
use App\Contributor;
use App\Organization;
use App\Program;
use App\Template;
use App\User;
use App\Meeting;
use App\Tenant;

class RegistrationTest extends TestCase
{
    use RefreshDatabase;

    /** @test */
    public function user_can_view_all_programs()
    {
        $tenant = factory(Tenant::class)->create();

        $response = $this->get("/{$tenant->slug}/programs/");

        $response->assertSee('Programs', $escaped = true);

    }
    
    /** @test */
    public function user_can_view_a_program_listing()
    {

        $program = factory(Program::class)->states('amCamp')->create();

        $tenantSlug = $program->contributors->first()->organization->tenant->slug;
        $response = $this->get("/{$tenantSlug}/programs/{$program->id}");

        $response->assertStatus(200);

        $response->assertSee('Factory Program', $escaped = true);
        $response->assertSee('This is a program generated by a factory.', $escaped = true);
        $response->assertSee('Dem pubnotez', $escaped = true);
        $response->assertSee('Grades', $escaped = true);
        $response->assertSee('5', $escaped = true);
        $response->assertSee('7', $escaped = true);

        
    }
}
