<?php

namespace Tests\Feature;

use Tests\TestCase;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Program;
use App\Order;
use App\Ticket;

class ViewOrderTest extends TestCase
{
    use RefreshDatabase;

    /** @test */
    function user_can_view_their_order_confirmation()
    {
        $program = factory(Program::class)->states('amCamp', 'published')->create()->addTickets(3);

        $order = factory(Order::class)->create([
            'confirmation_number' => 'ORDERCONFIRMATION1234',
            'amount' => 8500,
            'card_last_four' => '1881'
        ]);

        $tickeA = factory(Ticket::class)->create([
            'program_id' => $program->id,
            'order_id' => $order->id,
            'code' => 'TICKETCODE123'
        ]);

        $tickeB = factory(Ticket::class)->create([
            'program_id' => $program->id,
            'order_id' => $order->id,
            'code' => 'TICKETCODE456'
        ]);

        $response = $this->get("/orders/ORDERCONFIRMATION1234");

        $response->assertStatus(200);
        
        $response->assertViewHas('order', function ($viewOrder) use ($order) {
            return $order->id === $viewOrder->id;
        });

        $response->assertSee('ORDERCONFIRMATION1234');
        $response->assertSee('$85.00');
        $response->assertSee('**** **** **** 1881');
        $response->assertSee('TICKETCODE123');
        $response->assertSee('TICKETCODE456');
        $response->assertSee('Factory Program');
        $response->assertSee('This is a program generated by a factory.');
        $response->assertSee('Dem pubnotez');
    }

}